server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/blog-application-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Nivi-1627}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  jwt:
    secret: ${ACCESS_TOKEN_SECRET:blog_access_secret_super_secure_key_32chars}
    expiration-ms: ${ACCESS_TOKEN_EXPIRATION_MS:900000}
  cors:
    allowed-origins: ${CLIENT_URL:http://localhost:5173,https://blog-frontend.onrender.com}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
